# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 13:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('rooftop_area', models.PositiveIntegerField(blank=True, null=True)),
                ('consumption', models.PositiveIntegerField(blank=True, null=True)),
                ('total_bill_with_taxes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_unit_consumption', models.PositiveIntegerField(blank=True, null=True)),
                ('total_per_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('willing_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('price_escalation_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('plant_size_per_RT_area', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('plant_size_per_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('feasible_in_house_plant', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('consumer_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('cibil_report', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('min_amount_to_invest', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('max_amount_to_invest', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('IRR_value', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('financial_document_upload', models.FileField(blank=True, null=True, upload_to=users.models.image_upload_path)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'pm_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Basic_Assumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounting_factor', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_benefits_for_no_of_years', models.PositiveIntegerField(blank=True, null=True)),
                ('accelerated_depreciation', models.CharField(blank=True, max_length=64, null=True)),
                ('area_required_for_1KW_plant_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('electricity_generated_per_annum_per_kw', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_of_plant_including_batteries_for_1kw', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_of_plant_without_batteries_for_1kw', models.PositiveIntegerField(blank=True, null=True)),
                ('decrease_in_plant_output_1styear', models.PositiveIntegerField(blank=True, null=True)),
                ('decrease_in_plant_output_everyyear_after_1styear', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ebc_basic_assumptions',
            },
        ),
        migrations.CreateModel(
            name='EPC_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('registered_name', models.CharField(blank=True, max_length=64, null=True)),
                ('epc_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('about_epc', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=10, null=True)),
                ('projects_in_india', models.PositiveIntegerField(blank=True, null=True)),
                ('projects_outside_india', models.PositiveIntegerField(blank=True, null=True)),
                ('executed_projects', models.PositiveIntegerField(blank=True, null=True)),
                ('ongoing_projects', models.PositiveIntegerField(blank=True, null=True)),
                ('references_to_verify', models.CharField(blank=True, max_length=64, null=True)),
                ('cost_quality_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('annual_demand', models.PositiveIntegerField(blank=True, null=True)),
                ('bid_for_building_plant', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('feasible_in_house_plant', models.CharField(blank=True, max_length=64, null=True)),
                ('module_manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('inverter_manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('wiring_cost_range', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('civil_work_range', models.CharField(blank=True, max_length=64, null=True)),
                ('labor', models.CharField(blank=True, max_length=64, null=True)),
                ('total_cost_range', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('sme_range', models.CharField(blank=True, max_length=64, null=True)),
                ('cibil', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pm_epc_details',
            },
        ),
        migrations.CreateModel(
            name='Project_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc_Details', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_details', models.CharField(blank=True, max_length=64, null=True)),
                ('units_generated', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('no_of_units_generated', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('revenue', models.PositiveIntegerField(blank=True, null=True)),
                ('operation_and_maintainance', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('miscellaneous', models.CharField(blank=True, max_length=200, null=True)),
                ('commission_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('epc_review', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_consumer', to=settings.AUTH_USER_MODEL)),
                ('epc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_epc', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_investor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ebc_project_details',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'db_table': 'ebc_project_status',
            },
        ),
        migrations.CreateModel(
            name='Solar_Estimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_toparea_info', models.CharField(blank=True, max_length=64, null=True)),
                ('solution_for', models.CharField(choices=[('home', 'Home'), ('society', 'Society'), ('industry', 'industry')], max_length=20)),
                ('consumption_per_month', models.CharField(blank=True, max_length=64, null=True)),
                ('avg_bill_per_month', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('pin', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='/^(\\+\\d{1,3}[- ]?)?\\d{10}$/')])),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pm_solar_estimator',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pm_user_type',
            },
        ),
        migrations.AddField(
            model_name='project_details',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usertype', to='users.UserType'),
        ),
    ]
