# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171207_0650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment_details',
            table='pm_payment_details',
        ),
    ]
