# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171207_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
