# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171204_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
