# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171205_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='user_type',
            new_name='name',
        ),
    ]
